[versions]
agp = "8.2.0"
kotlin = "1.9.22"
coroutines = "1.7.3"

[libraries]
# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.2" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.5.0" }

# SQLDelight
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version = "2.0.1" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version = "2.0.1" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version = "3.5.3" }
koin-android = { module = "io.insert-koin:koin-android", version = "3.5.3" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version = "3.5.3" }

# Navigation
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version = "1.0.0" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version = "1.0.0" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version = "1.0.0" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version = "2.0.1" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
